const ingredientsTableData = [
  {
    title: "Vegetables",
    arr: [
      "onions",
      "spinach",
      "cucumbers",
      "alfalfa",
      "celery",
      "carrots",
      "split beans",
      "soy beans",
      "cabbage",
      "eggplant",
      "kale",
      "baby carrots",
      "soy sprout",
      "boychok",
      "green onion",
    ],
  },

  {
    title: "Meat",
    arr: [
      "chicken",
      "goat",
      "meat",
      "fish",
      "shrimp",
      "turkey",
      "bacon",
      "ham",
      "hot dogs",
      "Prosciutto",
      "salami",
      "sausages",
      "chorizo",
      "duck",
      "saitan",
    ],
  },
  {
    title: "Fruits",
    arr: [
      "apples",
      "pears",
      "citrus",
      "oranges",
      "grapefruits",
      "mandarin",
      "limes",
      "lemon",
      "stone fruit",
      "nectarines",
      "apricots",
      "peaches",
      "plums",
      "bananas",
      "mangoes",
      "strawberries",
      "raspberries",
      "blueberries",
      "kiwifruit",
      "passionfruit",
      "mamon",
    ],
  },
  {
    title: "Grains",
    arr: [
      "teff",
      "wheat",
      "oats",
      "rice",
      "corn",
      "barley",
      "sorghum",
      "rye",
      "millet",
      "triticale",
      "amaranth",
      "buckwheat",
      "quinoa",
      "arroz",
      "flour",
    ],
  },
  {
    title: "Seafood",
    arr: [
      "halibut",
      "mahi",
      "monkfish",
      "mullet",
      "parrotfish",
      "seabass",
      " perch",
      "salmon",
      "sardine",
      "sturgeon",
      "shark",
      "tilapia",
      "halibut",
      "mahi",
      "monkfish",
    ],
  },
];

export default ingredientsTableData;

// const vegetables = [
//   "onions",
//   "spinach",
//   "cucumbers",
//   "alfalfa",
//   "celery",
//   "carrots",
//   "split beans",
//   "soy beans",
//   "cabbage",
//   "eggplant",
//   "kale",
//   "baby carrots",
//   "soy sprout",
//   "boychok",
//   "green onion",
// ];

// const meats = [
//   "chicken",
//   "goat",
//   "meat",
//   "fish",
//   "shrimp",
//   "turkey",
//   "bacon",
//   "ham",
//   "hot dogs",
//   "Prosciutto",
//   "salami",
//   "sausages",
//   "chorizo",
//   "duck",
//   "saitan",
// ];

// const fruits = [
//   "apples",
//   "pears",
//   "citrus",
//   "oranges",
//   "grapefruits",
//   "mandarin",
//   "limes",
//   "lemon",
//   "stone fruit",
//   "nectarines",
//   "apricots",
//   "peaches",
//   "plums",
//   "bananas",
//   "mangoes",
//   "strawberries",
//   "raspberries",
//   "blueberries",
//   "kiwifruit",
//   "passionfruit",
//   "mamon",
// ];

// const grains = [
//   "teff",
//   "wheat",
//   "oats",
//   "rice",
//   "corn",
//   "barley",
//   "sorghum",
//   "rye",
//   "millet",
//   "triticale",
//   "amaranth",
//   "buckwheat",
//   "quinoa",
//   "arroz",
//   "flour",
// ];

// const seafood = [
//   "halibut",
//   "mahi",
//   "monkfish",
//   "mullet",
//   "parrotfish",
//   "seabass",
//   " perch",
//   "salmon",
//   "sardine",
//   "sturgeon",
//   "shark",
//   "tilapia",
//   "halibut",
//   "mahi",
//   "monkfish",
// ];
